; Development PHP settings
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On
error_log = /dev/stderr

memory_limit = 512M
max_execution_time = 60
post_max_size = 32M
upload_max_filesize = 32M

opcache.enable = 1
opcache.enable_cli = 0
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
opcache.jit = off

date.timezone = Europe/Prague

[xdebug]
xdebug.mode = ${XDEBUG_MODE}
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.start_with_request = trigger
xdebug.idekey = PHPSTORM
xdebug.discover_client_host = 1
