<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260427082748 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE listing (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_id INT NOT NULL, title VARCHAR(255) NOT NULL, detail_url VARCHAR(500) DEFAULT NULL, current_price INT DEFAULT NULL, price_by_agreement BOOLEAN NOT NULL, mileage_km INT DEFAULT NULL, manufacturing_date DATE DEFAULT NULL, in_operation_date DATE DEFAULT NULL, model_seo VARCHAR(50) NOT NULL, model_name VARCHAR(50) NOT NULL, additional_model_name VARCHAR(200) DEFAULT NULL, fuel VARCHAR(30) DEFAULT NULL, gearbox VARCHAR(30) DEFAULT NULL, location_district VARCHAR(100) DEFAULT NULL, location_municipality VARCHAR(100) DEFAULT NULL, listed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_edited_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, first_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, removed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, raw_data JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CB0048D49F75D7B0 ON listing (external_id)');
        $this->addSql('CREATE INDEX idx_listing_active ON listing (removed_at)');
        $this->addSql('CREATE TABLE price_snapshot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price INT NOT NULL, observed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, listing_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4EFB2E22D4619D1A ON price_snapshot (listing_id)');
        $this->addSql('CREATE INDEX idx_price_snapshot_listing_observed ON price_snapshot (listing_id, observed_at)');
        $this->addSql('CREATE TABLE scrape_run (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, listings_seen INT NOT NULL, listings_added INT NOT NULL, listings_price_changed INT NOT NULL, listings_marked_removed INT NOT NULL, error_text TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE price_snapshot ADD CONSTRAINT FK_4EFB2E22D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE price_snapshot DROP CONSTRAINT FK_4EFB2E22D4619D1A');
        $this->addSql('DROP TABLE listing');
        $this->addSql('DROP TABLE price_snapshot');
        $this->addSql('DROP TABLE scrape_run');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
